const actionTypes = {
  SET_MENU: "SET_MENU",
  SET_STORE_INFO: "SET_STORE_INFO",
  SET_AUTH: "SET_AUTH",
  SET_PERMISSIONS: "SET_PERMISSIONS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  RESET_SESSION: "RESET_SESSION",
  SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
  LANGUAGE_SESSION: "LANGUAGE_SESSION",
  CALLBACK_LANGUAGE: "CALLBACK_LANGUAGE",
  SET_SELECTED_STORE_ID: "SET_SELECTED_STORE_ID",
  SET_CURRENT_STEP_START_POS: "SET_CURRENT_STEP_START_POS",
};

export default actionTypes;
